### ISSUE TITLE
launching Streamlit for final project

### ISSUE THREAD

**Issue by akratch** [CMU-IDS-2020/fp-holmesandwatson#1]
Hi! Sorry I was side tracked from other deadlines and missed the piazza response from Dominik. We would like help in launching our Streamlit application similarly to the previous project. All of our Streamlit is contained in one file, so it shouldn't be too bad. Thank you!

**Comment by domoritz** [comment]
https://share.streamlit.io/cmu-ids-2020/fp-holmesandwatson/main/Final_Project_Streamlit.py

**Comment by domoritz** [comment]
There seems to be a problem with the deployment, though.

**Comment by akratch** [comment]
Hi Dominik! Thank you for launching the streamlit - it looks like the issue is with missing module tweepy. Tweepy is necessary for certain functionality of our interaction but we can remove it if it’s not possible to use this package on Streamlit share. Let us know what we can do to get it launched! Thank you!

**Comment by domoritz** [comment]
It should work if it's specified in the requirements file. See https://docs.streamlit.io/en/stable/deploy_streamlit_app.html. Not sure what's going wrong.

**Comment by akratch** [comment]
I modified some of the requirements that appear to have been deprecated, I am trying to alternatively deploy to heroku now, but it may work with streamlit share now that I got rid of PIL and re.

**Comment by akratch** [comment]
After a bit of work - it's working! Here it is: https://holmesandwatson.herokuapp.com

**Comment by domoritz** [comment]
Thanks. Streamlit also works now.
